New-PSUScript -Name "Users - Never Logged On.ps1" -Path "Reports\Users - Never Logged On.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Without Manager.ps1" -Path "Reports\Users - Without Manager.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Recently Modified.ps1" -Path "Reports\Users - Recently Modified.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Recently Created.ps1" -Path "Reports\Users - Recently Created.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Inactive Users.ps1" -Path "Reports\Users - Inactive Users.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Recently Deleted.ps1" -Path "Reports\Users - Recently Deleted.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Users - Locked Out.ps1" -Path "Reports\Users - Locked Out.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Computers - Inactive.ps1" -Path "Reports\Computers - Inactive.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Computers - Disabled.ps1" -Path "Reports\Computers - Disabled.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "Computers - Domain Controllers.ps1" -Path "Reports\Computers - Domain Controllers.ps1" -InformationAction "SilentlyContinue"